Accecibilty features
NabilHY/portfolio1 pull request #10
Opened 2022-02-22 14:57 UTC by NabilHY

-Me and my coding partner made changes to my portfolio website so that it's more accessible

2022-02-22 15:09 UTC, NabilHY commented on index.html
> +    <title>Portfolio's Main Page</title>
#10 Issue  Found : Previous webpage title was not

2022-02-22 17:58 UTC, Deepakdanger requested changes
Hi @Benmuiruri & @nabster13 , 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-22 17:58 UTC, Deepakdanger commented on index.html
>              <p>Hello I'm a software developer! I can help you build a product , feature or website Look
- [ ] From line no. 177 to 188 - All the image `alt` text is similar. Please give alt with appropriate alternative text for all the image.
- [ ] From line 235 to 241 - All input fields are missing form label. Please add label to each input field to resolve this accessibility issue.
- [ ] On line 44, 175, and 226 all the text has contrast issue. Please fix all these three text to make your website more accessible for all kind of users. 

You can check all these issue in the [aditus tool](https://www.aditus.io/button-contrast-checker/) and [WAVE tool extension](https://wave.webaim.org/).

2022-02-23 09:03 UTC, Benmuiruri commented
Hi @Deepakdanger thanks for the review. :pray: 

@NabilHY and I made the following changes 

- made each image alt unique
- Added the label element for all inputs
- Updated the footer background to improve the contrast.

2022-02-23 10:35 UTC, elmar8287 approved these changes
Hi, @NabilHY.

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

![](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-23 10:39 UTC, merged